### ISSUE TITLE
New Response classes

### ISSUE THREAD

**Issue by rodkings** [tparnell8/Untappd.Net#13]
Hey @tparnell8, is there any fast way to generate those response classes with Json properties?

**Comment by TerribleDev** [comment]
I used http://jsonutils.com/ make sure you check  Pascal Case and then make sure you wrap all of the classes inside their own namespace.

**Comment by TerribleDev** [comment]
@rodkings it spits out a lot of classes if you look at https://github.com/tparnell8/Untappd.Net/blob/master/src/Untappd.Net/Responses/UserBadges.cs you will see I wrapped that inside its own namespace to prevent conflicts, and then I had the root class inherit from UnAuthenticatedRequest I assume for Authenticated ones you will want to inherit from the AuthenicatedRequest https://github.com/tparnell8/Untappd.Net/blob/master/src/Untappd.Net/Request/AuthenticatedRequest.cs

**Comment by rodkings** [comment]
@tparnell8 great, I will use the same. I think it's fine about the amount of classes.
I tried a different solution for these inheritances. The problem is the UserBadges, for example, can be requested as both Authenticated and Unauthenticated. I created a BasicRequest, that implements IRequest. Created two new interfaces, IAuthenticatedRequest and IUnAuthenticated requests that inherits from IRequest. Now, each response Classes is inheriting BasicRequest, the interfaces that defines if needs authentication, or both.
On the repository, for authenticated requests, I'm using IAuthenticatedRequest as parameter of credentials. So you can use the same class for both authenticated and non-auth requests. Some responses classes will have only IAuthenticatedRequest, so you got the picture.

**Comment by rodkings** [comment]
@tparnell8 ops, IAuthenticatedRequest for TResult.
where TResult : IAuthenticatedRequest, new()

**Comment by TerribleDev** [comment]
That makes sense, and sounds like what I was going to do...

**Comment by TerribleDev** [comment]
Basically what was/am trying to accomplish was the use of typing to prevent people from trying to use an Authenticated request with a non authenticated token.

**Comment by TerribleDev** [comment]
Sounds like you are making it happen, which is awesome!

**Comment by rodkings** [comment]
Right now it looks like this:
public TResult Get<TResult>(IAuthenticatedUntappdCredentials credentials, string parameter = "", IDictionary<string, string> bodyParameters = null)
            where TResult : IAuthenticatedRequest, new()

the problem is that IAuthenticadUntappdCredentials and IUnAuthenticatedUntappdCredentials, both inherits from IUntappdCredentials.

**Comment by tparnell8** [comment]
do you need my help to de-tangle this mess? or do you got it? I assume you can figure out an elegant solution.

**Comment by TerribleDev** [comment]
@rodkings 

I see what the problem is...have AuthenticatedUntappdCredentials also inherit from the correct interface

``` csharp
   public sealed class AuthenticatedUntappdCredentials : UnAuthenticatedUntappdCredentials, IAuthenticatedUntappdCredentials

```

**Comment by TerribleDev** [comment]
That will allow it to use the proper get overload

**Comment by rodkings** [comment]
@tparnell8 very close to my solution, I will make a pull request, and yes, I need your help to solve this. Can you take a look?
