### ISSUE TITLE
Implement OAuth

### ISSUE THREAD

**Issue by TerribleDev** [tparnell8/Untappd.Net#2]
We should have some way to get an OAuth token. [Example](https://github.com/RockstarLabs/OwinOAuthProviders/pull/75)

**Comment by rodkings** [comment]
Do you want to implement a full OAuth authentication? Only the token should be enough, or not?

**Comment by TerribleDev** [comment]
@rodkings we should provide a way so that someone could get an auth token, so we can use the parts of the API that require one. maybe a class where you can call into it with the redirect endpoint string, the user of this could implement that endpoint elsewhere, and then could capture the token.

**Comment by TerribleDev** [comment]
@rodkings if you want to tackle this I am more than happy to assign this issue to you.

**Comment by TerribleDev** [comment]
@rodkings if you want to tackle this I am more than happy to assign this issue to you.

**Comment by rodkings** [comment]
I will be glad to help. Right now, I really need to make authenticated requests, so, I was thinking of implementing first authenticated requests and later, provide a way to get the token. Right now I already have a MVC app getting the token with the Owin provider. What do you think?

**Comment by TerribleDev** [comment]
@rodkings thats totally fine man

**Comment by TerribleDev** [comment]
I'll give this a shot in the meantime :)

**Comment by rodkings** [comment]
@tparnell8 Great, I will probably start as soon as I fix some EF6 issues on my app.
